version: '3.0'

services:
  mongodb:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - ./db:/data/db

  bot:
    image: bot:1.0
    build:
      context: ./
      dockerfile: Dockerfile
    links:
     - mongodb
    #command: ['top']
    command: ['python3', '/home/bot/bot/bot.py', '${SLACK_BOT_TOKEN}', '${BOT_ID}']

