version: '3.0'

services:
  mongodb:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - ./db:/data/db
    restart: always
    environment:
     - MONGODB_USER: '${DB_USER_ENV}'
     - MONGODB_DATABASE: '${DB_NAME_ENV}'
     - MONGODB_PASS: '${DB_PASS}'
